@startuml
skinparam handwritten true
title Enviar Informativos por Email

frame "Enviar Informativo" {
  component "Selecionar Categoria"
  component "Selecionar Usuário"
  component "Assunto"
  component "Mensagem"
  component "Enviar"
}
@enduml