
@startsalt
{+
  {^"Inscrição"}
  "Nome Completo:            "
  "Matricula:                "
  ^Curso^
  "Disciplina:               "
  "Data da monitoria:        "
  ()Monitoria Online
  "Alunos monitorados: 1     "
  "Nome Completo:            "
  "Matricula:                "
  "Tema:                     "
  {
    [ Enviar ] | [ Cancelar ]
  }
}
@endsalt
