@startsalt
{+
    "Alunos Inscritos:              "
    "Professor X esta disponivel as:"
    O email do candidato Patrick Gougeon é invalido
    Matricula: XXXXXXXXXX
    [Enviar Emails]
}
@endsalt
