@startsalt
{+
  {^"Enviar Informativo"}
  "Selecionar Categoria:    "
  "Selecionar Usuário:      "
  "Assunto:                 "
  "Mensagem:                "
  {
    [ Enviar ] | [ Cancelar ]
  }
}
@endsalt
