@startsalt
{+
  {^"Formulario"}
  "Nome Completo:            "
  "Matricula:                "
  ^Curso^
  "Disciplina:               "
  "Data da monitoria:        "
  ()Monitoria Online
  "Alunos monitorados: 0     "
  {
    [ Enviar ] | [ Cancelar ]
  }
}
@endsalt
