# Generated by Django 5.2.7 on 2025-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
    ]
