# Generated by Django 5.2.7 on 2025-10-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalvagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='curso',
        ),
        migrations.AlterField(
            model_name='vaga',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portalvagas.disciplina'),
        ),
    ]
