# Generated by Django 5.2.7 on 2025-10-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalvagas', '0002_disciplina_remove_vaga_curso_alter_vaga_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
    ]
