@startuml

' Definição das classes
class User 
class Aluno {
    - matricula: String
    - nome: String
    - email

    + seCandidatar(): void
}
class Professor {
    - nome: String
    - email: String

    + aprovarCandidato(c: Candidato): void
    + verRelatorioAcompanhamento(): void

}
class "CASA (organizador)" as CASA {
    - nome: String
    - email: String
    - senha: String
    
    + enviarInformativosEmail(): void
}
class Candidato {
    - status: String
}
class Monitorado {
    + preencherRelatorioExperiencia(): void
}
class "Teaching Assistant" as TA {
    - aluno: Aluno
    + preencherFormularioFrequencias(): void
}
class Disciplina {
    - nome: String
    - monitor: Teaching Assistant
    - area: String
}
class Inscricao {
    - disciplina: Disciplina
    - alunos: Candidato[]
}
class Entrevista {
    - aluno: Candidato
}
class SessaoMonitoria

' Relacionamentos de Herança (Generalização)
' Um Aluno, Professor e CASA são tipos de Usuário.
User <|-down- Aluno
User <|-down- Professor
User <|-down- CASA

' Candidato, Monitor e TA são papéis/especializações de um Aluno.
Aluno <|-down- Candidato
Aluno <|-down- Monitorado
Aluno <|-down- TA

' Relacionamentos de Associação com Multiplicidade
' O fluxo de inscrição e entrevista
Candidato "1" --> "1..*" Inscricao : realiza
Inscricao "*" --> "1" Disciplina : é para
Inscricao "1" --> "0..1" Entrevista : pode gerar
Entrevista "1" --> "1..*" Candidato : entrevista
Entrevista "1" --> "1..*" Professor : conduzida por
CASA "1" --> "0..*" Entrevista : agendada por

' O fluxo de monitoria e acompanhamento
TA "*" --> "*" Disciplina : atua na
TA "1" --> "0..*" SessaoMonitoria : registra
SessaoMonitoria "*" --> "1" Disciplina : é sobre
Professor "1" --> "0..*" TA : supervisiona
CASA "1" --> "0..*" TA : acompanha

@enduml
