@startuml DiagramaUC
' Define a direção do diagrama da esquerda para a direita
left to right direction

' Atores
actor Organizador
actor Aluno
actor Sistema

' Casos de Uso
rectangle Programa {
  ' Casos de uso
  usecase "Aprovar Inscrições" as UC1
  usecase "Rejeitar Inscrições" as UC2
  usecase "Inscrever-se no programa" as UC3
}

' Relações
Organizador --> UC1
Organizador --> UC2
Sistema --> UC2
Sistema --> UC1
Aluno --> UC3

@enduml