# Generated by Django 5.2.7 on 2025-10-23 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CASA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlunoMonitorado',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asClasses.aluno')),
                ('aulas_participadas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('asClasses.aluno',),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asClasses.aluno')),
                ('status', models.CharField(default='pendente', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('asClasses.aluno',),
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('agendada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_agendadas', to='asClasses.casa')),
                ('professores', models.ManyToManyField(related_name='entrevistas', to='asClasses.professor')),
                ('candidatos', models.ManyToManyField(related_name='entrevistas', to='asClasses.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='asClasses.disciplina')),
                ('monitorados', models.ManyToManyField(blank=True, related_name='sessoes', to='asClasses.alunomonitorado')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='asClasses.disciplina')),
                ('entrevista', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricao', to='asClasses.entrevista')),
                ('alunos', models.ManyToManyField(blank=True, related_name='inscricoes', to='asClasses.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asClasses.aluno')),
                ('acompanhada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tas_acompanhadas', to='asClasses.casa')),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='teaching_assistants', to='asClasses.disciplina')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisionados', to='asClasses.professor')),
            ],
            options={
                'abstract': False,
            },
            bases=('asClasses.aluno',),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitora_disciplina', to='asClasses.teachingassistant'),
        ),
    ]
