# Generated by Django 5.2.7 on 2025-11-01 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('curso', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_historico', models.FileField(upload_to='historicos/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appofc.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appofc.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'arquivo_historico')},
            },
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
