# Generated by Django 5.2.7 on 2025-11-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0002_aluno_inscricao_delete_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
