# Generated by Django 5.2.7 on 2025-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0003_alter_disciplina_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='vaga',
            name='unidade',
            field=models.CharField(choices=[('Barra', 'Campus Barra'), ('Centro', 'Campus Centro')], default='Barra', max_length=20),
        ),
    ]
