# Generated by Django 5.2.7 on 2025-11-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0004_remove_vaga_periodo_alter_vaga_unidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaga',
            unique_together={('disciplina', 'unidade')},
        ),
    ]
