# Generated by Django 5.2.7 on 2025-11-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0005_alter_vaga_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('vaga', 'aluno')},
        ),
    ]
