# Generated by Django 5.2.7 on 2025-11-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0006_alter_inscricao_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
    ]
