# Generated by Django 5.2.7 on 2025-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0009_curso_alter_disciplina_nome_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.CharField(choices=[('adm', 'Administração'), ('arquitetura', 'Arquitetura e Urbanismo'), ('ciencias_economicas', 'Ciências Econômicas'), ('publicidade', 'Comunicação Social – Publicidade e Propaganda'), ('jornalismo', 'Jornalismo'), ('direito', 'Direito'), ('engcivil', 'Engenharia Civil'), ('engproducao', 'Engenharia de Produção'), ('engmecanica', 'Engenharia Mecânica'), ('tech', 'TECH'), ('relacoes_internacionais', 'Relações Internacionais')], default='adm', max_length=30),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('adm', 'Administração'), ('arquitetura', 'Arquitetura e Urbanismo'), ('ciencias_economicas', 'Ciências Econômicas'), ('publicidade', 'Comunicação Social – Publicidade e Propaganda'), ('jornalismo', 'Jornalismo'), ('direito', 'Direito'), ('engcivil', 'Engenharia Civil'), ('engproducao', 'Engenharia de Produção'), ('engmecanica', 'Engenharia Mecânica'), ('tech', 'TECH'), ('relacoes_internacionais', 'Relações Internacionais')], default='adm', max_length=30),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
