# Generated by Django 5.2.7 on 2025-11-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0010_alter_disciplina_curso_alter_aluno_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appofc.curso'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(related_name='disciplinas', to='appofc.curso'),
        ),
    ]
