# Generated by Django 5.2.7 on 2025-11-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0011_curso_remove_disciplina_curso_alter_disciplina_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
