# Generated by Django 5.2.7 on 2025-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0012_alter_curso_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CANDIDATURA APROVADA', 'Candidatura Aprovada'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
